name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: az-pipeline-config

pool: Azure Pipelines

stages:
  - stage: Build
    jobs:
    - job: Build
      pool:
          name: Azure Pipelines
      steps:
      - task: Bash@3
        displayName: Install .NET 
      - bash: |
          # git clone https://github.com/phuongnv196/udacity-project-3.git
          # sudo apt-get update
          # sudo apt-get install dotnet-sdk-6.0
          echo $(System.DefaultWorkingDirectory)
          echo $(Pipeline.Workspace)
          # dotnet --version
        displayName: Install .NET 6.0
      - task: Bash@3
        displayName: Build .NET project
      - bash: |
          # cd ../$(System.DefaultWorkingDirectory)/fakerestapi/FakeRESTApi.Web
          # dotnet build --configuration release
          echo "Build done"
        displayName: Install .NET 6.0
      # - task: ArchiveFiles@2
      #   displayName: Archive FakeRestAPI
      #   inputs:
      #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/fakerestapi/FakeRESTApi.Web/bin/release/net6.0'
      #     includeRootFolder: false
      #     archiveType: 'zip'
      #     archiveFile: '$(Build.BuildId)-fakerestapi.zip'
      # - task: PublishPipelineArtifact@1
      #   displayName: Upload package
      #   inputs:   
      #     targetPath: $(Build.BuildId)-fakerestapi.zip
      #     artifact: drop-fakerestapi

      # - task: ArchiveFiles@2
      #   displayName: Archive Selenium
      #   inputs:
      #     rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
      #     includeRootFolder: false
      #     archiveType: 'zip'
      #     archiveFile: '$(Build.BuildId)-selenium.zip'
      #     replaceExistingArchive: true
        
      # - task: PublishPipelineArtifact@1
      #   displayName: Upload Selenium
      #   inputs:
      #    targetPath: $(Build.BuildId)-selenium.zip
      #    artifact: drop-selenium