name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
  - group: az-pipeline-config

pool: Default

stages:
  - stage: Infrastructure
    displayName: Azure Resources Create with terraform
    jobs:
    - job: TerraformTasks
      displayName: Terraform
      pool:
          name: Azure Pipelines
      steps:
      - task: DownloadSecureFile@1
        name: terraform
        displayName: Download terraform.tfvars
        inputs:
          secureFile: 'terraform.tfvars'

      - checkout: self
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'

      - task: Bash@3
        displayName: Copy terraform.tfvars
        inputs:
          targetType: 'inline'
          script: cp $(Agent.TempDirectory)/terraform.tfvars $(System.DefaultWorkingDirectory)/terraform/environments/test

      # Needed for Terraform VM deployment
      - task: InstallSSHKey@0
        displayName: Key for SSH to VM
        inputs:
          knownHostsEntry: '$(knownHostsEntry)'
          sshPublicKey: '$(sshPublicKey)'
          sshKeySecureFile: 'id_rsa'


      - task: TerraformTaskV2@2
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
          backendServiceArm: 'udacity-deploy-service-connection'
          backendAzureRmResourceGroupName: 'udacity-phuongnv19-project03-rg'
          backendAzureRmStorageAccountName: '$(StorageAccountName)'
          backendAzureRmContainerName: 'phuongnv19container'
          backendAzureRmKey: 'terraform.tfstate'
          

      - task: TerraformTaskV2@2
        displayName: Terraform Validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
          backendServiceArm: 'udacity-deploy-service-connection'
      - task: TerraformTaskV2@2
        displayName: Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
          environmentServiceNameAzureRM: 'udacity-deploy-service-connection'
      - task: TerraformTaskV2@2
        displayName: Terraform Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: |
            -auto-approve
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
          environmentServiceNameAzureRM: 'udacity-deploy-service-connection'

  - stage: Build
    jobs:
    - job: Build
      pool:
          name: Azure Pipelines
      steps:
      - task: Bash@3
        displayName: Install .NET 
      - bash: |
          sudo apt-get update
          sudo apt-get install dotnet-sdk-6.0
          echo "Install .NET done!"
          dotnet --version
        displayName: Install .NET 6.0
      - task: Bash@3
        displayName: Build .NET project
      - bash: |
          cd $(System.DefaultWorkingDirectory)/fakerestapi/FakeRESTApi.Web
          dotnet build --configuration release
          echo "Build done"
        displayName: Install .NET 6.0
      - task: ArchiveFiles@2
        displayName: Archive FakeRestAPI
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/fakerestapi/FakeRESTApi.Web/bin/release/net6.0'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.BuildId)-fakerestapi.zip'
      - task: PublishPipelineArtifact@1
        displayName: Upload package
        inputs:   
          targetPath: $(Build.BuildId)-fakerestapi.zip
          artifact: drop-fakerestapi

      - task: ArchiveFiles@2
        displayName: Archive Selenium
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.BuildId)-selenium.zip'
          replaceExistingArchive: true
        
      - task: PublishPipelineArtifact@1
        displayName: Upload Selenium
        inputs:
         targetPath: $(Build.BuildId)-selenium.zip
         artifact: drop-selenium
  - stage: DeployApp
    displayName: Deploy App to Custom VM
    jobs:
    - deployment: FakeRestAPI
      pool:
          name: Azure Pipelines
      environment: 'VM-TEST'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureWebApp@1
              displayName: 'Deploy Azure Web App'
              inputs:
                azureSubscription: 'udacity-deploy-service-connection'
                appName: 'udacity-phuongnv19-project03-app-AppService'
                appType: webApp
                package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
                deploymentMethod: auto          

    - deployment: VMDeploy
      displayName: VMDeploy
      environment:
        name:  'VM-TEST'
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  #! /bin/bash
                  sudo apt-get upgrade -y
                  sudo apt-get install python3-pip -y
                  sudo apt-get install unzip -y
                  sudo apt-get install -y chromium-browser
                  pip3 install selenium

                  # download chrome driver
                  FILE=chromedriver_linux64.zip
                  if [ -f "$FILE" ]; then
                    echo "$FILE exists."
                  else
                    wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
                  fi
                  # install chrome driver
                  unzip chromedriver_linux64.zip
                  sudo mv chromedriver /usr/bin/chromedriver
                  sudo chown root:root /usr/bin/chromedriver
                  sudo chmod +x /usr/bin/chromedriver
                  chromium-browser -version
                  chromedriver --version
                  # agent log analytics
              env:  # To use secret variables in a script, we must explicitly map them as environment variables.
                AZURE_LOG_ANALYTICS_ID: $(AZURE_LOG_ANALYTICS_ID)
                AZURE_LOG_ANALYTICS_PRIMARY_KEY: $(AZURE_LOG_ANALYTICS_PRIMARY_KEY)
              displayName: Configure VM   
  - stage: Test
    jobs:
      - deployment: test_on_vm
        displayName: UI testing
        environment:
         name: 'VM-TEST'
         resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Bash@3
                  inputs:
                   targetType: inline
                   script: |
                    #!/bin/bash
                    chromium-browser -version
                    chromedriver --version
                    cd $(Pipeline.Workspace)/drop-selenium
                    unzip -o $(Build.BuildId)-selenium.zip
                    sudo mkdir -p /var/log/selenium
                    sudo chmod 664 /var/log/selenium
                    python3 uitest.py > ui-logs.log
                    python3 uitest.py
                    sudo mv ui-logs.log /var/log/selenium
                    cd $(System.DefaultWorkingDirectory)
                    mkdir -p log/selenium
                    sudo cp /var/log/selenium/ui-logs.log log/selenium
                - task: PublishPipelineArtifact@1
                  displayName: Publish selenium logs
                  inputs:
                    targetPath: '$(System.DefaultWorkingDirectory)/log/selenium/ui-logs.log'
                    artifactName: 'drop-selenium-logs'
                    
      - job: Test_Post_man
        displayName: Postman Test
        pool:
          name: Azure Pipelines
        steps: 
          - task: NodeTool@0
            displayName: Install Node v16.X
            inputs:
              versionSpec: '16.x'
          - bash: |
              node -v
              sudo npm install -g newman
              newman -v
            displayName: Install Newman CLI
          - bash: |
                newman run automatedtesting/postman/StarterAPIs.json --reporters cli,junit --reporter-junit-export Results/RegressionTests.xml --suppress-exit-code
            displayName: Run Regression Test
          - task: CmdLine@2
            inputs:
              script: 'ls'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
          - task: PublishTestResults@2
            displayName: Publish report postman
            condition: always()
            inputs:
             testResultsFormat: JUnit
             testResultsFiles: '$(System.DefaultWorkingDirectory)/Results/*.xml'

      - job: Test_Jmeter
        displayName: Performance testing
        pool:
          name: Azure Pipelines
        steps:
          - bash: |
              sudo apt-get install openjdk-11-jre-headless -y
              java -version
              wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz -O jmeter.tgz
              tar xzvf jmeter.tgz
              echo "####################"
              echo "jmeter version : " 
              apache-jmeter-5.5/bin/jmeter --version   
              echo "####################"
              mkdir -p log/jmeter
              pwd
              ls -la
              ls '$(Pipeline.Workspace)/s'
            displayName: Install JMeter
          - bash: |
              apache-jmeter-5.5/bin/jmeter -n -t automatedtesting/jmeter/StressTest.jmx -l log/jmeter/stress-test-result.csv -e -f -o log/jmeter/stress-test-html-report -j log/jmeter/jmeter-stress-test.log
              cat log/jmeter/jmeter-stress-test.log
              ls '$(Pipeline.Workspace)/s'
              ls '$(Pipeline.Workspace)/s/automatedtesting/jmeter'
            displayName: Stress Test
          - bash: |
              apache-jmeter-5.5/bin/jmeter -n -t automatedtesting/jmeter/EnduranceTest.jmx -l log/jmeter/endurance-test-result.csv -e -f -o log/jmeter/endurance-test-html-report -j log/jmeter/jmeter-endurance-test.log
              cat log/jmeter/jmeter-endurance-test.log
            displayName: Endurance Test
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'automatedtesting/jmeter'
              ArtifactName: 'jmeter'
              publishLocation: 'Container'  